# Generated by Django 5.0.6 on 2025-09-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_role_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('dop', 'Director of Photography'), ('gaffer', 'Gaffer'), ('first_ac', 'First AC'), ('grip', 'Grip'), ('admin', 'Admin')], default='grip', max_length=50),
        ),
    ]
