# Generated by Django 5.0.6 on 2025-09-26 07:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('setup_type', models.CharField(choices=[('camera', 'Camera'), ('lighting', 'Lighting'), ('grip', 'Grip')], default='camera', max_length=50)),
                ('department', models.CharField(choices=[('dop', 'Director of Photography'), ('first_ac', '1st AC'), ('gaffer', 'Gaffer'), ('grip', 'Grip')], default='dop', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Setup',
                'verbose_name_plural': 'Setups',
                'ordering': ['-created_at'],
            },
        ),
    ]
