# Generated by Django 5.2.5 on 2025-08-23 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='setup',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='setups', to='setups.tag'),
        ),
    ]
