# Generated by Django 5.2.5 on 2025-08-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setup',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='setup',
            name='department',
            field=models.CharField(choices=[('dop', 'Director of Photography'), ('first_ac', '1st AC'), ('gaffer', 'Gaffer'), ('grip', 'Grip')], default='dop', max_length=50),
        ),
        migrations.AddField(
            model_name='setup',
            name='setup_type',
            field=models.CharField(choices=[('camera', 'Camera'), ('lighting', 'Lighting'), ('grip', 'Grip')], default='camera', max_length=50),
        ),
        migrations.AlterField(
            model_name='setup',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
