# Generated by Django 5.2.5 on 2025-08-20 13:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('scene_type', models.CharField(choices=[('interview', 'Interview'), ('int_night', 'Interior Night'), ('ext_day', 'Exterior Day'), ('car_chase', 'Car Chase'), ('music_video', 'Music Video'), ('docu_run', 'Docu Run & Gun')], max_length=32)),
                ('description', models.TextField()),
                ('camera', models.CharField(max_length=120)),
                ('lens', models.CharField(max_length=120)),
                ('focal_length_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('frame_rate', models.CharField(blank=True, max_length=40)),
                ('shutter', models.CharField(blank=True, max_length=40)),
                ('iso', models.CharField(blank=True, max_length=40)),
                ('white_balance', models.CharField(blank=True, max_length=40)),
                ('lights', models.TextField(help_text='List lights used (one per line or CSV)')),
                ('modifiers', models.TextField(blank=True, help_text='Diffusion, flags, grids, etc.')),
                ('environment', models.CharField(max_length=80)),
                ('mood', models.CharField(choices=[('natural', 'Natural'), ('moody', 'Moody'), ('high_key', 'High Key'), ('dramatic', 'Dramatic'), ('warm', 'Warm'), ('cool', 'Cool')], max_length=32)),
                ('budget_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16)),
                ('diagram_image', models.ImageField(blank=True, null=True, upload_to='diagrams/')),
                ('bts_image', models.ImageField(blank=True, null=True, upload_to='bts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='setups', to='setapp.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
