# Generated by Django 5.2.5 on 2025-08-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setups',
            name='camera',
            field=models.CharField(help_text='Camera used, e.g., ARRI Alexa Mini, BMPCC 6K', max_length=120),
        ),
        migrations.AlterField(
            model_name='setups',
            name='environment',
            field=models.CharField(help_text='e.g., Overcast, Studio, Daylight', max_length=80),
        ),
        migrations.AlterField(
            model_name='setups',
            name='frame_rate',
            field=models.CharField(blank=True, help_text='e.g., 24fps, 50fps', max_length=40),
        ),
        migrations.AlterField(
            model_name='setups',
            name='lens',
            field=models.CharField(help_text='Lens used, e.g., Sigma 18-35, Cooke S4 32mm', max_length=120),
        ),
        migrations.AlterField(
            model_name='setups',
            name='shutter',
            field=models.CharField(blank=True, help_text='e.g., 180°, 1/50', max_length=40),
        ),
    ]
